 [build]
  command = "npm install && npm run build"
  publish = "Frontend/build"

[build.environment]
  NODE_OPTIONS = "--max-old-space-size=8192"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
